### ISSUE TITLE
Style login page

### ISSUE THREAD

**Issue by NebuDev14** [project-lumiere/lumiere.codes#69]
Login page looks a bit desolate

![Current](https://user-images.githubusercontent.com/64022614/141397991-5c23f6e0-1804-4415-af49-a3ba08bba39f.png)

**Comment by AnthonyKuang** [comment]
Congrats on issue #69. Here's some "inspiration" if you will..
![tiktok](https://user-images.githubusercontent.com/61532649/141398566-52747125-ff19-4f15-912c-508167c665fe.png)

**Comment by NebuDev14** [comment]
Resolved this here: https://github.com/project-lumiere/lumiere.codes/pull/73
