### ISSUE TITLE
Team page

### ISSUE THREAD

**Issue by AnthonyKuang** [project-lumiere/lumiere.codes#71]
Generic team page needed to establish more trust with end users. A few `<Avatar />` components would be good, along with a short blurb from each team member.

- Link socials
- Short blurb
- Avatar

In the future, we will have a Figma wireframe designed by our Designer to work with. But as of current we don't have that luxury 😭 (I promise you I'm trying my hardest to find a designer tho!)

## How to do

- File to create: `pages/company/team.js`
- import and use <Avatar /> components from `@components/ui/Avatar`
- Ask team members for profile pic & description
- Use your best judgement
- Leave it unstyled if you're not confident in design
- Explore other files to see project-wide conventions
1. For example use `.container` class for content

**Comment by IamTregsthedev** [comment]
I can do this

I can just use the code from podcast.hackclub.com

**Comment by AnthonyKuang** [comment]
Would be great, but will need to onboard you on dev for this. Firstly,
check out https://lumiere.codes/resources/contributing and let me know if
you get stuck.

**Comment by NebuDev14** [comment]
Pretty sure the Avatar component is designed only for the Navbar (so it can have a dropdown menu w/ settings and such thats unique to the specific logged in user) so I don't think we can use it for the team page
