### ISSUE TITLE
Blog page

### ISSUE THREAD

**Issue by AnthonyKuang** [project-lumiere/lumiere.codes#72]
## Motivation

Startups need a blog to pump out a consistent flow of information to users. Good for establishing trust as well

See https://tailwind-nextjs-starter-blog.vercel.app, https://www.raycast.com/blog

## How to do it!

- All blog posts are stored in `posts/company/blog` in the repo
- Find the function `getAllSlugs` defined in `lib/mdxBundler` - this function outputs all of the files inside of a folder within `/post`
- In `pages/company/blog` call `getAllSlugs` inside of `getStaticProps` for static site generation speed
- Render a list of blog posts in the `return` of Blog, sorting by date created

**Comment by AnthonyKuang** [comment]
`getAllBlogPosts` is pretty much the same implementation as `getAllSlugs` found in `/lib/xdm`

**Comment by IamTregsthedev** [comment]
wouldn't it be cool if we use our own cms?

**Comment by AnthonyKuang** [comment]
It would. We don't have it built yet :((

**Comment by NebuDev14** [comment]
Sovled in PR #77
